[check]
ignore = [
    "C003", # 'implicit none' missing 'external'
    "S091", # file extension should be '.f90' or '.F90'
]
line-length = 132

# Exclude all build dirs
exclude =[
    "**build**",
    "./pfunit"
]

file-extensions = [
    "f90",
    "F90",
]
