FROM ghcr.io/carpentries-incubator/fortran-unit-testing:main

COPY --chown=vscode exercises/4-fortran-unit-test-syntax /home/vscode/4-fortran-unit-test-syntax

WORKDIR /home/vscode/4-fortran-unit-test-syntax/solution

# build tests with cmake
RUN cmake -B build -DCMAKE_PREFIX_PATH=/home/vscode/pfunit/build/installed && \
    cmake --build build

# test pfunit with ctest
RUN ctest --test-dir build --output-on-failure

