FROM ghcr.io/carpentries-incubator/modern-fortran:main

COPY --chown=vscode exercises/fortran-unit-test-syntax /home/vscode/fortran-unit-test-syntax

WORKDIR /home/vscode/fortran-unit-test-syntax/solution

# build tests with cmake
RUN cmake -B build-cmake -DCMAKE_PREFIX_PATH=/home/vscode/pfunit/build/installed && \
    cmake --build build-cmake

# test pfunit with ctest
RUN ctest --test-dir build-cmake --output-on-failure

# build tests with make
RUN make tests

# run make tests
RUN ./test/tests
