FROM ghcr.io/carpentries-incubator/modern-fortran:main

COPY --chown=vscode exercises/refactoring-fortran /home/vscode/refactoring-fortran

# Build challenge with cmake
WORKDIR /home/vscode/refactoring-fortran/challenge
RUN cmake -B build && \
    cmake --build build

# Build solution with cmake
WORKDIR /home/vscode/refactoring-fortran/solution
RUN cmake -B build && \
    cmake --build build
